update

diff --git a/.scripts/install b/.scripts/install
--- a/.scripts/install
+++ b/.scripts/install
@@ -14,7 +14,7 @@ function show_welcome_msg {
 	dialog \
 		--title "Bem-vindo!" \
 		--msgbox "Bem-vindo ao Auto Instalator Script do Rafael!\\n\\nEste script vai instalar e configurar seu desktop Arch Linux com i3wm." \
-		10 60 || { clear; exit; }
+		9 60 || { clear; exit; }
 }
 
 
@@ -36,29 +36,32 @@ function show_pre_install_msg {
 		--title "Aviso" \
 		--yes-label "Vomitão!" \
 		--no-label "Não, obrigado" \
-		--yesno "Este script vai executar a instalação de for totalmente automatizada.\\n\\nVai levar algum tempo, então senta e relaxa.\\n\\nPressione <Vomitão!> para iniciar a instalação." \
-		13 60 || { clear; exit; }
+		--yesno "Este script vai executar a instalação de forma totalmente automatizada.\\n\\nVai levar algum tempo, então senta e relaxa.\\n\\nPressione <Vomitão!> para iniciar a instalação." \
+		11 60 || { clear; exit; }
 }
 
 
 function install_from_package_list {
-	curl -sSL https://raw.githubusercontent.com/rtogo/.dotfiles/master/.scripts/package-list | sed '/^#/d' > /tmp/package-list
-	total=$(wc -l < /tmp/package-list)
+	tmpfile=$(mktemp)
+	trap "rm -f $tmpfile" EXIT
+	curl -sSL https://raw.githubusercontent.com/rtogo/.dotfiles/master/.scripts/package-list.csv | sed '/^#/d' > $tmpfile
+	total=$(wc -l < $tmpfile)
 	while IFS=, read -r package description; do
 		n=$((n+1))
+		description="${description%\"}"  # Remove o prefixo "
+		description="${description#\"}"  # Remove o sufixo "
 		install $package $description
-	done < /tmp/package-list
-	rm /tmp/package-list
-
+	done < $tmpfile
 }
 
 
 function install {
 	dialog \
 		--title "Instalação" \
-		--infobox "Instalando pacote $n de $total...\\n\\n$package: $description" \
-		7 70
-	sudo -u "$username" yay -S --noconfirm "$1" >/dev/null 2>&1
+		--infobox "Instalando software $n de $total: $package...\\n\\n\\n$description" \
+		8 70
+	sleep 0.1
+	#sudo -u "$username" yay -S --noconfirm "$1" >/dev/null 2>&1
 }
 
 
@@ -81,8 +84,8 @@ function install_dotfiles {
 function show_done_msg {
 	dialog \
 		--title "Tudo pronto!" \
-		--msgbox "Pronto! Supondo que não deu nenhum erro que foi omitido por estas janelas bonitinhas, o script foi executado com sucesso, todos os pacotes foram instalados, e os arquivos de configuração devem estar em seus lugares.\\n\\nReinice o computador para aplicar as configurações." \
-		9 80
+		--msgbox "Pronto! Supondo que não deu nenhum erro que foi omitido por estas janelas bonitinhas, o script foi executado com sucesso, todos os softwares foram instalados, e os arquivos de configuração devem estar em seus lugares.\\n\\nUm backup dos arquivos de configuração pré-existentes que seriam sobrescritos foi criado em ~/.dotfiles-backup.\\n\\nReinice o computador para aplicar as configurações." \
+		13 80
 }
 
 # ----------------
@@ -92,8 +95,8 @@ function show_done_msg {
 # Atualiza o sistema e ao mesmo tempo garante que está rodando como root
 pacman -Syu --noconfirm --needed dialog || error "Este script deve ser executado como root"
 
-#show_welcome_msg || error "Abortado."
-get_username
+show_welcome_msg || error "Abortado."
+get_username || error "Abortado."
 
 # Adiciona o usuário ao grupo wheel
 usermod -aG wheel $username
@@ -119,8 +122,8 @@ echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
 # Instala yay como AUR helper
 pacman --noconfirm --needed -S yay >/dev/null 2>&1
 
-install_from_package_list
-configure_docker
+install_from_package_list || error "Abortado."
+configure_docker || error "Abortado."
 install_dotfiles || error "Abortado."
 show_done_msg || error "Abortado."
 clear
