update

diff --git a/.scripts/install b/.scripts/install
--- a/.scripts/install
+++ b/.scripts/install
@@ -1,4 +1,6 @@
 #!/bin/bash
+PACKAGE_LIST=https://raw.githubusercontent.com/rtogo/.dotfiles/master/.scripts/package-list.csv
+DOTFILES_INSTALL_SCRIPT=https://raw.githubusercontent.com/rtogo/.dotfiles/master/.scripts/dotfiles-install
 
 # ---------
 # FUNCTIONS
@@ -44,7 +46,7 @@ function show_pre_install_msg {
 function install_from_package_list {
 	tmpfile=$(mktemp)
 	trap "rm -f $tmpfile" EXIT
-	curl -sSL https://raw.githubusercontent.com/rtogo/.dotfiles/master/.scripts/package-list.csv | sed '/^#/d' > $tmpfile
+	curl -sSL $PACKAGE_LIST | sed '/^#/d' > $tmpfile
 	total=$(wc -l < $tmpfile)
 	while IFS=, read -r package description; do
 		n=$((n+1))
@@ -60,8 +62,7 @@ function install {
 		--title "Instalação" \
 		--infobox "Instalando software $n de $total: $package...\\n\\n\\n$description" \
 		8 70
-	sleep 0.1
-	#sudo -u "$username" yay -S --noconfirm "$1" >/dev/null 2>&1
+	sudo -u "$username" yay -S --noconfirm "$1" >/dev/null 2>&1
 }
 
 
@@ -77,7 +78,20 @@ function install_dotfiles {
 		--title "Instalação" \
 		--infobox "Colocando arquivos de configuração no lugar..." \
 		7 70
-	curl -sSL https://raw.githubusercontent.com/rtogo/.dotfiles/master/.scripts/dotfiles-install | sudo -u "$username" /bin/bash >/dev/null 2>&1
+	curl -sSL $DOTFILES_INSTALL_SCRIPT | sudo -u "$username" /bin/bash >/dev/null 2>&1
+}
+
+
+function install_vim_plugins {
+	dialog \
+		--title "Instalação" \
+		--infobox "Instalando vim plugins..." \
+		7 70
+	# Para funcionar em modo non interactive, adicione "silent!" antes dos
+	# comandos que causam erros quando os plugins ainda não estão
+	#os plugins não existem instalados
+	/usr/bin/nvim +'PlugInstall --sync' +qa >/dev/null 2>&1
+	/usr/bin/vim +'PlugInstall --sync' +qa >/dev/null 2>&1
 }
 
 
@@ -116,7 +130,7 @@ sed -i 's/^#\s\(%wheel\sALL=(ALL)\s\NOPASSWD:\sALL\)/\1/' /etc/sudoers
 # Ativa cores no pacman e yay
 sed -i 's/^#Color/Color/g' /etc/pacman.conf
 
-# Disable the annoying beeps
+# Desliga os beeps
 echo "blacklist pcspkr" > /etc/modprobe.d/nobeep.conf
 
 # Instala yay como AUR helper
@@ -125,6 +139,7 @@ pacman --noconfirm --needed -S yay >/dev/null 2>&1
 install_from_package_list || error "Abortado."
 configure_docker || error "Abortado."
 install_dotfiles || error "Abortado."
+install_vim_plugins || error "Abortado."
 show_done_msg || error "Abortado."
 clear
 
